### ISSUE TITLE
How to access layers(cotp, tpkt and mms) on scapy

### ISSUE THREAD

**Issue by sh4d0wlesss** [rhelmke/iec61850_mms_scapy#1]
When ı try to get layers of mms packet ı get list of layers like this:

`['Ethernet', 'IP', 'TCP', 'TPKT', 'COTP', 'COTP Connection Request (CR)']
`

but I tried to access layers like `packet.getlayer(tpkt)` and i got an error 

`name 'tpkt' is not defined
`
How can i access the tpkt, cotp and mms layers?

**Comment by rhelmke** [comment]
Hey,

[packet.getlayer](https://scapy.readthedocs.io/en/latest/api/scapy.packet.html?highlight=getlayer#scapy.packet.Packet.getlayer) requires a class, and the `tpkt` symbol you used does not appear to be one :-).

When you import `iec61850_mms`, you should pass the `TPKT` class like this:


```python3
import iec61850_mms
import scapy

# [...]

layer = packet.getlayer(iec61850_mms.TPKT)
```

Hope this helps

**Comment by sh4d0wlesss** [comment]
Ah thanks, i understand it. 
I have another question, can ı access the data values like float values sent on mms packets?  When i try to print the packets the mms data send packets print the mms layer as raw data (all hex values), am i make something wrong?

Thanks again :)

**Comment by rhelmke** [comment]
Hey,

the packets are ordinary scapy [Packets](https://scapy.readthedocs.io/en/latest/api/scapy.packet.html).

According to the docs, you may use [show](https://scapy.readthedocs.io/en/latest/api/scapy.packet.html#scapy.packet.Packet.show), [show2](https://scapy.readthedocs.io/en/latest/api/scapy.packet.html#scapy.packet.Packet.show2), or e.g. [getfieldval](https://scapy.readthedocs.io/en/latest/api/scapy.packet.html#scapy.packet.Packet.getfieldval).

Please understand that this repository does only provide custom packet definitions for scapy. You're better of consulting the project's official docs.

Cheers and stay safe.
